import type { ConfidenceAssessment } from "@/lib/types";
import ConfidenceBadge from "./ConfidenceBadge";

interface ConfidencePanelProps {
  confidence: ConfidenceAssessment;
  recommendedResearch: string[];
  usage?: { inputTokens: number; outputTokens: number };
  durationMs: number | null;
  clarificationNote?: string;
}

const CONFIDENCE_METER: Record<string, { width: string; color: string }> = {
  high:   { width: "w-full",  color: "bg-emerald-500" },
  medium: { width: "w-2/3",   color: "bg-amber-400" },
  low:    { width: "w-1/3",   color: "bg-rose-400" },
};

export default function ConfidencePanel({ confidence, recommendedResearch, usage, durationMs, clarificationNote }: ConfidencePanelProps) {
  const meter = CONFIDENCE_METER[confidence.overall] ?? CONFIDENCE_METER.low;

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      {/* Confidence card */}
      <div className="border border-gray-200 rounded-xl bg-white p-5">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-sm font-semibold text-gray-900">Evidence Confidence</h2>
            {confidence.sample_size_note && (
              <p className="text-xs text-gray-400 mt-0.5">{confidence.sample_size_note}</p>
            )}
          </div>
          <ConfidenceBadge level={confidence.overall} size="md" />
        </div>

        {/* Confidence meter */}
        <div className="mb-4">
          <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
            <div className={`h-full ${meter.width} ${meter.color} rounded-full transition-all`} />
          </div>
        </div>

        {confidence.rationale && (
          <p className="text-xs font-medium text-gray-700 leading-relaxed mb-2">{confidence.rationale}</p>
        )}
        {confidence.notes && (
          <p className="text-xs text-gray-500 leading-relaxed mb-3">{confidence.notes}</p>
        )}

        {confidence.limitations.length > 0 && (
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Limitations</p>
            <ul className="space-y-1.5">
              {confidence.limitations.map((lim, i) => (
                <li key={i} className="flex items-start gap-2">
                  <svg className="w-3 h-3 text-amber-400 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                  </svg>
                  <p className="text-xs text-gray-600 leading-relaxed">{lim}</p>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* High trust suitability */}
        <div className={`mt-4 flex items-start gap-2.5 rounded-lg p-3 border ${
          confidence.suitable_for_high_trust_use
            ? "bg-emerald-50 border-emerald-200"
            : "bg-rose-50 border-rose-200"
        }`}>
          {confidence.suitable_for_high_trust_use ? (
            <svg className="w-3.5 h-3.5 text-emerald-500 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
          ) : (
            <svg className="w-3.5 h-3.5 text-rose-500 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
            </svg>
          )}
          <div>
            <p className={`text-xs font-semibold uppercase tracking-wide mb-0.5 ${confidence.suitable_for_high_trust_use ? "text-emerald-700" : "text-rose-700"}`}>
              {confidence.suitable_for_high_trust_use ? "Suitable for high-trust use" : "Not suitable for high-trust use"}
            </p>
            {!confidence.suitable_for_high_trust_use && confidence.high_trust_notes && (
              <p className="text-xs text-rose-700 leading-relaxed">{confidence.high_trust_notes}</p>
            )}
          </div>
        </div>

        {/* Clarification note — only shown for low confidence, generated by fallback re-prompt */}
        {clarificationNote && confidence.overall === "low" && (
          <div className="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-lg">
            <p className="text-xs font-semibold text-amber-700 uppercase tracking-wide mb-1.5">What to do next</p>
            <p className="text-xs text-amber-800 leading-relaxed">{clarificationNote}</p>
          </div>
        )}
      </div>

      {/* Next research + stats card */}
      <div className="border border-gray-200 rounded-xl bg-white p-5">
        <h2 className="text-sm font-semibold text-gray-900 mb-4">Recommended Next Research</h2>
        {recommendedResearch.length > 0 ? (
          <ul className="space-y-2.5">
            {recommendedResearch.map((r, i) => (
              <li key={i} className="flex items-start gap-2.5">
                <div className="w-5 h-5 rounded-full bg-brand-50 border border-brand-100 flex items-center justify-center shrink-0 mt-0.5">
                  <span className="text-xs font-bold text-brand-600">{i + 1}</span>
                </div>
                <p className="text-xs text-gray-600 leading-relaxed">{r}</p>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-xs text-gray-400">No further research recommendations.</p>
        )}

        {/* Usage stats */}
        {(usage || durationMs) && (
          <div className="mt-5 pt-4 border-t border-gray-100 grid grid-cols-2 gap-3">
            {durationMs && (
              <div className="text-center p-2.5 bg-gray-50 rounded-lg border border-gray-100">
                <p className="text-base font-semibold text-gray-700">{(durationMs / 1000).toFixed(1)}s</p>
                <p className="text-xs text-gray-400 mt-0.5">duration</p>
              </div>
            )}
            {usage && (
              <div className="text-center p-2.5 bg-gray-50 rounded-lg border border-gray-100">
                <p className="text-base font-semibold text-gray-700">{((usage.inputTokens + usage.outputTokens) / 1000).toFixed(1)}k</p>
                <p className="text-xs text-gray-400 mt-0.5">tokens used</p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
